INSERT INTO Categorys (parent, name, parent_name)
VALUES 
(1, N'Ốp lưng-Bao da', N'Phụ kiện điện thoại'),
(1, N'Dán màn hình', N'Phụ kiện điện thoại'),
(1, N'Kính cường lực', N'Phụ kiện điện thoại'),
(1, N'Dây sạc, củ sạc', N'Phụ kiện điện thoại'),
(1, N'Pin sạc dự phòng', N'Phụ kiện điện thoại'),
(1, N'Giá đỡ - Kẹp điện thoại', N'Phụ kiện điện thoại'),
(1, N'Thẻ nhớ', N'Phụ kiện điện thoại'),
(2, N'Bàn phím cơ', N'Phụ kiện máy tính'),
(2, N'Chuột, lót chuột', N'Phụ kiện máy tính'),
(2, N'Giá đỡ laptop - Tay đỡ màn hình', N'Phụ kiện máy tính'),
(2, N'Balo - Túi xách', N'Phụ kiện máy tính'),
(2, N'Đầu chuyển đổi dữ liệu', N'Phụ kiện máy tính'),
(2, N'Ổ cứng - Thẻ nhớ', N'Phụ kiện máy tính'),
(3, N'Camera hành trình', N'Phụ kiện camera'),
(3, N'Camera an ninh', N'Phụ kiện camera'),
(3, N'Gimbal', N'Phụ kiện camera'),
(3, N'Tripod', N'Phụ kiện camera'),
(3, N'Thẻ nhớ', N'Phụ kiện camera'),
(4, N'Tai nghe', N'Phụ kiện âm thanh, ánh sáng'),
(4, N'Loa', N'Phụ kiện âm thanh, ánh sáng'),
(4, N'Micro', N'Phụ kiện âm thanh, ánh sáng'),
(4, N'Đèn học', N'Phụ kiện âm thanh, ánh sáng'),
(4, N'Đèn ngủ', N'Phụ kiện âm thanh, ánh sáng'),
(4, N'Đèn trang trí', N'Phụ kiện âm thanh, ánh sáng'),
(5, N'Router Wifi', N'Phụ kiện khác'),
(5, N'Bộ phát Wifi di động', N'Phụ kiện khác'),
(5, N'Tay cầm chơi game', N'Phụ kiện khác'),
(5, N'Quạt tản nhiệt', N'Phụ kiện khác');